export const productsArray = [
  {
    id: "1",
    name: "Jacket 1",
    description: "A nice blue jacket",
    image: "img/blue_jacket.png",
    price: 999,
    size: "Small",
  },
  {
    id: "2",
    name: "Jacket 1",
    description: "A nice blue jacket",
    image: "img/blue_jacket.png",
    price: 1099,
    size: "Medium",
  },
  {
    id: "3",
    name: "Jacket 1",
    description: "A nice blue jacket",
    image: "img/blue_jacket.png",
    price: 1199,
    size: "Large",
  },
  {
    id: "4",
    name: "Jacket 2",
    description: "A great green jacket",
    image: "img/green_jacket.png",
    price: 1299,
    size: "Small",
  },
  {
    id: "5",
    name: "Jacket 2",
    description: "A great green jacket",
    image: "img/green_jacket.png",
    price: 1399,
    size: "Medium",
  },
  {
    id: "6",
    name: "Jacket 2",
    description: "A great green jacket",
    image: "img/green_jacket.png",
    price: 1449,
    size: "Large",
  },
  {
    id: "7",
    name: "Jacket 3",
    description: "A warm red jacket",
    image: "img/red_jacket.png",
    price: 699,
    size: "Small",
  },
  {
    id: "8",
    name: "Jacket 3",
    description: "A warm red jacket",
    image: "img/red_jacket.png",
    price: 749,
    size: "Medium",
  },
  {
    id: "9",
    name: "Jacket 3",
    description: "A warm red jacket",
    image: "img/red_jacket.png",
    price: 799,
    size: "Large",
  },
  {
    id: "10",
    name: "Jacket 4",
    description: "A cool yellow jacket",
    image: "img/yellow_jacket.png",
    price: 499,
    size: "Small",
  },
  {
    id: "11",
    name: "Jacket 4",
    description: "A cool yellow jacket",
    image: "img/yellow_jacket.png",
    price: 549,
    size: "Medium",
  },
  {
    id: "12",
    name: "Jacket 4",
    description: "A cool yellow jacket",
    image: "img/yellow_jacket.png",
    price: 649,
    size: "Large",
  },
];
