// export const productsArray = [
//   {
//     id: "16",
//     name: "Mt. Maclure",
//     color: "Blue",
//     description: "A nice blue jacket",
//     image: "img/blue_jacket.png",
//     price: 999,
//     size: "Small",
//   },
//   {
//     id: "17",
//     name: "Mt. Maclure",
//     color: "Blue",
//     description: "A nice blue jacket",
//     image: "img/blue_jacket.png",
//     price: 1099,
//     size: "Medium",
//   },
//   {
//     id: "18",
//     name: "Mt. Maclure",
//     color: "Blue",
//     description: "A nice blue jacket",
//     image: "img/blue_jacket.png",
//     price: 1199,
//     size: "Large",
//   },
//   {
//     id: "22",
//     name: "Glacier Point",
//     color: "Green",
//     description: "A great green jacket",
//     image: "img/green_jacket.png",
//     price: 1299,
//     size: "Small",
//   },
//   {
//     id: "23",
//     name: "Glacier Point",
//     color: "Green",
//     description: "A great green jacket",
//     image: "img/green_jacket.png",
//     price: 1399,
//     size: "Medium",
//   },
//   {
//     id: "24",
//     name: "Glacier Point",
//     color: "Green",
//     description: "A great green jacket",
//     image: "img/green_jacket.png",
//     price: 1449,
//     size: "Large",
//   },
//   {
//     id: "28",
//     name: "Kuna Peak",
//     color: "Red",
//     description: "A warm red jacket",
//     image: "img/red_jacket.png",
//     price: 699,
//     size: "Small",
//   },
//   {
//     id: "29",
//     name: "Kuna Peak",
//     color: "Red",
//     description: "A warm red jacket",
//     image: "img/red_jacket.png",
//     price: 749,
//     size: "Medium",
//   },
//   {
//     id: "30",
//     name: "Kuna Peak",
//     color: "Red",
//     description: "A warm red jacket",
//     image: "img/red_jacket.png",
//     price: 799,
//     size: "Large",
//   },
//   {
//     id: "34",
//     name: "Sheperd Crest",
//     color: "Yellow",
//     description: "A cool yellow jacket",
//     image: "img/yellow_jacket.png",
//     price: 499,
//     size: "Small",
//   },
//   {
//     id: "35",
//     name: "Sheperd Crest",
//     color: "Yellow",
//     description: "A cool yellow jacket",
//     image: "img/yellow_jacket.png",
//     price: 549,
//     size: "Medium",
//   },
//   {
//     id: "36",
//     name: "Sheperd Crest",
//     color: "Yellow",
//     description: "A cool yellow jacket",
//     image: "img/yellow_jacket.png",
//     price: 599,
//     size: "Large",
//   },
// ];
